services:
  - type: web
    name: takeoff
    env: node
    rootDir: backend
    preDeployCommand: npm ci && npm run build
    buildCommand: npm install
    startCommand: node server.js
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000
      - key: OPENAI_API_KEY
        sync: false
